[project]
name = "yvideo_pg"
version = "0.1.0"
description = "Django admin for old clojure/react Y-video"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django==4.0.10",
    "psycopg2-binary==2.9.3",
]
