SITE_NAME = "someSite" # humhelp.byu.edu is an example
SAML_SETTINGS = {
    'strict': True, # must be set to True in production in order to be secure.
    'debug': False, # must be set to False in production to be secure.
    'sp': {
        # the metadata generated by this endpoint will be used by OIT to allow for authentication from their idp (identity provider) server. this is the "sp" (service provider) metadata
        # If you don't want to provide a url, you can instead call this URL yourself, copy the data that is there and send that to the appropriate OIT member.
        'entityId': f'https://{SITE_NAME}/metadata',
        'assertionConsumerService': {
            'url': f'https://{SITE_NAME}/?acs',
            'binding': 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST',
        },
        'singleLogoutService': {
            'url': f'https://{SITE_NAME}/?sls',
            'binding': 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
        },
        'NameIDFormat': 'urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified',
        'x509cert': '',
        'privateKey': '',
    },
    'idp': {
        'entityId': 'https://cas.byu.edu/cas/idp/metadata',
        'singleSignOnService': {
            'url': 'https://cas.byu.edu/cas/idp/profile/SAML2/Redirect/SSO',
            'binding': 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
        },
        'singleLogoutService': {
            'url': 'https://cas.byu.edu/cas/idp/profile/SAML2/Redirect/SLO',
            'binding': 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
        },
        # If only one x509 cert is used for signing and encryption (e.g. you only see one x509) then put the x509 cert string in the commented out 'x509cert': field.
        # If separate x509s are used for sigining and encryption, place the appropriate x509 cert strings in the fields you see below.
        # 'x509cert': '',
        'x509certMulti': {
            'signing': [
                ''
            ],
            'encryption': [
                ''
            ]
        }
    },
}
